version: "3"
networks:
  expense:
    driver: bridge
volumes:
  mysql: # docker volume create mysql

#use pre-existing network
# networks:
#   network1:
#     name: expense
#     external: true

services:
  mysql:
    image: srikanthhg/mysql:expense
    env_file: "expense-docker/mysql/.env"
    container_name: mysql  # --name mysql
    volumes:
      - mysql:/var/lib/mysql  # -v mysql:/var/lib/mysql
      # - ./path_to_init_scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # -h  means host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: srikanthhg/backend:expense
    container_name: backend
    # command: sh -c "./mysql-check.sh -- node /opt/server/index.js"
    command: sh -c "until mysqladmin ping -h mysql --silent; do echo waiting for mysql; sleep 2; done && node /opt/server/index.js"
    # command: sh -c "sleep 10 && node /opt/server/index.js"
    depends_on: 
      - mysql
    deploy:
      # replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: 512M

  frontend:
    image: srikanthhg/frontend:expense
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M





# On a typical Linux system, the log file is located at:
# /var/lib/docker/containers/[container-id]/[container-id]-json.log
# For production environments, consider integrating a centralized logging system for better log management and analysis.
# docker-compose up --scale backend=3
# donot mention container_name when u mention replicas
