version: "3"
networks:
  expense:
    driver: bridge
volumes:
  mysql: # docker volume create mysql

#use pre-existing network
# networks:
#   network1:
#     name: expense
#     external: true

services:
  mysql:
    image: srikanthhg/mysql:expense
    env_file: "expense-docker/mysql/.env"
    container_name: mysql  # --name mysql
    volumes:
      - mysql:/var/lib/mysql  # -v mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # -h  means host

  backend:
    image: srikanthhg/backend:expense
    container_name: backend
    command: sh -c "./mysql-check.sh -- node /opt/server/index.js"
    # command: sh -c "sleep 10 && node /opt/server/index.js"
    depends_on: 
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
  frontend:
    image: srikanthhg/frontend:expense
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M

