apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
        tier: db 
        project: expense # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: srikanthhg/mysql:expense
        # env:
        # - name: MYSQL_ROOT_PASSWORD # This is the name of the environment variable
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql  # This is the name of the ConfigMap
        #       key: MYSQL_ROOT_PASSWORD   # This is the key in the ConfigMap

        # envFrom:
        #   - configMapRef:
        #       name: mysql       #name of the configmap

        volumeMounts:
        - name: dbpass
          mountPath: "/config"
          readOnly: true

  
  # volumeClaimTemplates:
  # - metadata

  # volumes:
  # - name: dbpass
  #   configMap:
  #     name: mysql # Provide the name of the ConfigMap you want to mount.

      